### ISSUE TITLE
Update version on npm

### ISSUE THREAD

**Issue by hm1996** [Xetera/ghost-cursor#7]
Can you please release the last changes to npm?

**Comment by Niek** [comment]
+1 for this, @Xetera can you push an update please?

**Comment by Niek** [comment]
Latest build is now published after each build as an artifact: https://github.com/Xetera/ghost-cursor/actions (select the top one, download the artifact).

In order to publish to NPM @Xetera needs to set the `NPM_TOKEN` secret, see https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets - is that possible @Xetera?

**Comment by Niek** [comment]
Added NPM auto-publish when creating new tags. v1.0.4 has been released now: https://www.npmjs.com/package/ghost-cursor
