### ISSUE TITLE
Cursor Doesn't work in Page.evaluate function

### ISSUE THREAD

**Issue by lelly8484** [Xetera/ghost-cursor#84]
If I try to pass in cursor to page.evaluate function, it says Error: Evaluation failed: TypeError: cursor.click is not a function. Will it not work in page.evaluate?

**Comment by Niek** [comment]
Can you please provide a snippet?

**Comment by Xetera** [comment]
The `page.evaluate` callback along with all its parameters get serialized and sent to the browser over the wire. Functions you pass as a parameter (including `cursor.click`) and anything else captured inside a closure won't work. They can't be serialized and sent to the client for the same reason you can't get a function out of a `fetch()` call.

You need to treat whatever is running in the evaluate function as if it lives in a completely different machine and communicate with it through message passing which will require you to return whatever values are relevant from `page.evaluate` and call `page.click()` back on the puppeteer side of things.

Instead of writing code like this:

```ts
// ❌ not good | `cursor.click` can't be sent even when passed as a parameter
page.evaluate((cursor) => {
  if (window.innerWidth > someValue) {
    cursor.click(someElement)
  }
}, cursor)
```

you would refactor it to just use `page.evaluate` to pull relevant info down to puppeteer-land.
```ts
// ✅ works | no dependency on cursor inside the evaluate function
const pageWidth = await page.evaluate(() => {
  return window.innerWidth
})

if (pageWidth > someValue) {
  cursor.click(someElement)
}
```
